# Run Backtest Rank

Run z-score mean-reversion backtests on all cointegrated pairs (or a capped subset), then show the **top 10 pairs by Sharpe ratio**. Use the printed `PAIRS` list in `pairs_backtest.ipynb`.

In [13]:
import sys
from datetime import timedelta
from pathlib import Path

import pandas as pd

_root = Path.cwd().resolve()
while _root != _root.parent and not (_root / ".git").exists():
    _root = _root.parent
sys.path.insert(0, str(_root))

from research.functions.load_data import load_prices
from research.functions.backtest_pair import backtest_pair

PROCESSED_DIR = _root / "research" / "processed"
DATA_DIR = _root / "data"
COINT_CSV = PROCESSED_DIR / "cointegration_results_5pct_noncollinear.csv"

In [14]:
# ── Config ─────────────────────────────────────────────────────────
MAX_PAIRS = 10_000   # None = all ~72k pairs; 10_000 runs in a few minutes
TOP_N = 50

LOOKBACK = 60
ENTRY_Z = 2.0
EXIT_Z = 0.0
CAPITAL = 100_000
COST_BPS = 5
MIN_TRADES = 5

In [15]:
print("Loading cointegration results...")
coint = pd.read_csv(COINT_CSV)
coint = coint.sort_values("pvalue", ascending=True).reset_index(drop=True)
if MAX_PAIRS is not None:
    coint = coint.head(MAX_PAIRS)
pairs_list = list(coint[["ticker1", "ticker2"]].itertuples(index=False, name=None))
all_tickers = list({t for p in pairs_list for t in p})
print(f"Backtesting {len(pairs_list):,} pairs ({len(all_tickers)} unique tickers)...")

Loading cointegration results...
Backtesting 10,000 pairs (1243 unique tickers)...

In [16]:
print("Loading price data...")
prices = load_prices(
    tickers=all_tickers,
    data_dir=DATA_DIR,
    columns=["date", "ticker", "adj_close"],
)
prices["date"] = pd.to_datetime(prices["date"]).dt.date
wide = prices.pivot(index="date", columns="ticker", values="adj_close").sort_index()

max_date = wide.index.max()
end_date = max_date - timedelta(days=365)
wide = wide.loc[wide.index <= end_date]
print(f"Backtest range: {wide.index.min()} to {wide.index.max()} ({len(wide)} days)")

Loading price data...
Backtest range: 2020-01-02 to 2025-02-18 (1289 days)

In [17]:
results = []
for i, (a, b) in enumerate(pairs_list):
    if (i + 1) % 5000 == 0 or i == 0:
        print(f"  {i + 1:,} / {len(pairs_list):,} pairs...")
    res = backtest_pair(wide, a, b, LOOKBACK, ENTRY_Z, EXIT_Z, CAPITAL, COST_BPS)
    if "error" in res:
        continue
    results.append(res)  # keep pnl_series for YoY / geom-mean table

summary = pd.DataFrame([{k: v for k, v in r.items() if k != "pnl_series"} for r in results])

  1 / 10,000 pairs...
  5,000 / 10,000 pairs...
  10,000 / 10,000 pairs...

In [18]:
if summary.empty:
    print("No valid backtest results.")
else:
    summary = summary[summary["n_trades"] >= MIN_TRADES].copy()
    print(f"Pairs with at least {MIN_TRADES} trades: {len(summary):,}")
    summary = summary.sort_values(["sharpe", "n_trades"], ascending=[False, False]).reset_index(drop=True)
    top = summary.head(TOP_N)
    print(f"Top {TOP_N} pairs by Sharpe ratio (then n_trades):")
    display(top)
    pairs_out = [(r["ticker_a"], r["ticker_b"]) for _, r in top.iterrows()]
    print("# PAIRS for pairs_backtest.ipynb:")
    print("PAIRS =", pairs_out)

Pairs with at least 5 trades: 8,971
Top 50 pairs by Sharpe ratio (then n_trades):

,pair,ticker_a,ticker_b,days,total_pnl,total_cost,sharpe,yearly_growth_pct,mean_daily_pnl,std_daily_pnl,n_trades
0,CURB/SOXX,CURB,SOXX,37,35997.97,300.0,7.641,711.83,972.92,2021.31,6
1,CURB/TAN,CURB,TAN,37,31046.02,300.0,6.575,530.60,839.08,2025.80,6
2,CURB/IRDM,CURB,IRDM,37,37981.88,250.0,6.490,795.99,1026.54,2510.90,5
3,PFBC/SOLV,PFBC,SOLV,164,157044.46,450.0,5.708,326.59,957.59,2662.95,9
4,APLS/SOLV,APLS,SOLV,164,182402.82,250.0,4.368,392.95,1112.21,4041.89,5
5,COP/WAY,COP,WAY,113,55658.55,400.0,3.181,168.26,492.55,2458.10,8
6,PMT/SOLV,PMT,SOLV,164,60494.42,350.0,3.098,106.87,368.87,1890.11,7
7,D/GEV,D,GEV,163,57709.65,250.0,2.931,102.25,354.05,1917.74,5
8,CURB/DOW,CURB,DOW,37,9863.28,250.0,2.849,89.78,266.58,1485.30,5
9,APLE/VSTS,APLE,VSTS,288,75195.62,350.0,2.805,63.34,261.10,1477.62,7
10,DXC/VSTS,DXC,VSTS,288,203480.28,400.0,2.800,164.16,706.53,4005.71,8
11,CURB/INSP,CURB,INSP,37,9372.24,250.0,2.684,84.07,253.30,1498.42,5
12,CURB/TFX,CURB,TFX,37,15337.27,250.0,2.424,164.28,414.52,2714.39,5
13,BNO/EMBC,BNO,EMBC,669,149516.22,1150.0,2.407,41.12,223.49,1474.07,23
14,NCLH/TIP,NCLH,TIP,895,1091557.55,1350.0,2.388,100.91,1219.62,8106.29,27
15,EWZ/JNJ,EWZ,JNJ,1083,1063435.56,1500.0,2.272,77.00,981.93,6859.54,30
16,EMBC/WINA,EMBC,WINA,669,724547.55,950.0,2.272,121.37,1083.03,7568.80,19
17,HAFC/SOLV,HAFC,SOLV,164,136612.14,350.0,2.244,275.61,833.00,5891.73,7
18,GDEN/VSTS,GDEN,VSTS,288,139937.25,400.0,2.220,115.07,485.89,3474.97,8
19,EMBC/KTB,EMBC,KTB,669,784838.52,1100.0,2.217,127.33,1173.15,8402.03,22
20,INN/PLD,INN,PLD,854,703265.22,1000.0,2.132,84.93,823.50,6131.59,20
21,NCLH/VXF,NCLH,VXF,1122,1014946.80,1550.0,2.105,71.87,904.59,6821.22,31
22,IQV/OXY,IQV,OXY,875,578036.63,1400.0,2.050,73.54,660.61,5115.86,28
23,EG/MBC,EG,MBC,487,141182.76,750.0,2.037,57.71,289.90,2258.72,15
24,OXY/YOU,OXY,YOU,622,164767.46,900.0,2.035,48.36,264.90,2066.10,18
25,EMBC/KR,EMBC,KR,669,747678.81,1150.0,2.033,123.69,1117.61,8725.82,23
26,EG/SOLV,EG,SOLV,164,36553.46,400.0,2.008,61.40,222.89,1761.99,8
27,DXC/PZZA,DXC,PZZA,1228,836867.32,1550.0,2.003,58.27,681.49,5399.80,31
28,NABL/SRPT,NABL,SRPT,840,417540.77,1350.0,1.987,63.75,497.07,3971.83,27
29,SPY/VTIP,SPY,VTIP,904,570099.98,1550.0,1.984,69.94,630.64,5045.76,31
30,SNCY/VIS,SNCY,VIS,633,814541.75,950.0,1.967,141.36,1286.80,10382.76,19
31,EMBC/SXI,EMBC,SXI,669,662852.34,1000.0,1.960,114.98,990.81,8024.99,20
32,EMBC/GO,EMBC,GO,669,452944.74,1000.0,1.951,90.44,677.05,5508.60,20
33,EMBC/IRDM,EMBC,IRDM,669,733535.58,850.0,1.942,122.28,1096.47,8964.33,17
34,NCLH/SM,NCLH,SM,1228,889125.68,1900.0,1.932,60.04,724.04,5948.15,38
35,GPI/SYK,GPI,SYK,1228,1022053.57,2050.0,1.926,64.24,832.29,6861.39,41
36,AHCO/SOLV,AHCO,SOLV,164,88915.68,350.0,1.917,165.77,542.17,4488.81,7
37,CCL/SNEX,CCL,SNEX,1228,1190383.08,1800.0,1.913,69.02,969.37,8043.44,36
38,NCLH/WAFD,NCLH,WAFD,1228,1276843.62,1650.0,1.868,71.28,1039.77,8834.59,33
39,NCLH/RJF,NCLH,RJF,1228,1454215.45,1700.0,1.842,75.59,1184.21,10207.95,34
40,BDX/TTWO,BDX,TTWO,1228,357995.55,1800.0,1.840,36.65,291.53,2514.47,36
41,GPN/VSTS,GPN,VSTS,288,171107.59,450.0,1.821,139.33,594.12,5180.12,9
42,REYN/VAW,REYN,VAW,1208,583504.62,1750.0,1.813,49.33,483.03,4230.56,35
43,DGX/WMT,DGX,WMT,995,714125.71,1550.0,1.811,70.08,717.71,6290.74,31
44,CERT/TIP,CERT,TIP,656,319365.74,900.0,1.804,73.45,486.84,4284.11,18
45,NBHC/WAFD,NBHC,WAFD,1228,1098774.25,1850.0,1.797,66.48,894.77,7903.37,37
46,HWM/NRG,HWM,NRG,1228,785087.34,1850.0,1.796,56.43,639.32,5651.58,37
47,AXL/UPS,AXL,UPS,1228,1314516.06,1950.0,1.778,72.23,1070.45,9558.92,39
48,CCL/EBAY,CCL,EBAY,1228,1013850.79,1750.0,1.764,63.99,825.61,7429.72,35
49,REYN/VFH,REYN,VFH,1208,542001.07,2050.0,1.756,47.39,448.68,4056.31,41

# PAIRS for pairs_backtest.ipynb:
PAIRS = [('CURB', 'SOXX'), ('CURB', 'TAN'), ('CURB', 'IRDM'), ('PFBC', 'SOLV'), ('APLS', 'SOLV'), ('COP', 'WAY'), ('PMT', 'SOLV'), ('D', 'GEV'), ('CURB', 'DOW'), ('APLE', 'VSTS'), ('DXC', 'VSTS'), ('CURB', 'INSP'), ('CURB', 'TFX'), ('BNO', 'EMBC'), ('NCLH', 'TIP'), ('EWZ', 'JNJ'), ('EMBC', 'WINA'), ('HAFC', 'SOLV'), ('GDEN', 'VSTS'), ('EMBC', 'KTB'), ('INN', 'PLD'), ('NCLH', 'VXF'), ('IQV', 'OXY'), ('EG', 'MBC'), ('OXY', 'YOU'), ('EMBC', 'KR'), ('EG', 'SOLV'), ('DXC', 'PZZA'), ('NABL', 'SRPT'), ('SPY', 'VTIP'), ('SNCY', 'VIS'), ('EMBC', 'SXI'), ('EMBC', 'GO'), ('EMBC', 'IRDM'), ('NCLH', 'SM'), ('GPI', 'SYK'), ('AHCO', 'SOLV'), ('CCL', 'SNEX'), ('NCLH', 'WAFD'), ('NCLH', 'RJF'), ('BDX', 'TTWO'), ('GPN', 'VSTS'), ('REYN', 'VAW'), ('DGX', 'WMT'), ('CERT', 'TIP'), ('NBHC', 'WAFD'), ('HWM', 'NRG'), ('AXL', 'UPS'), ('CCL', 'EBAY'), ('REYN', 'VFH')]

In [19]:
import numpy as np
top_pairs = set(zip(top["ticker_a"], top["ticker_b"]))
top_results = [r for r in results if (r["ticker_a"], r["ticker_b"]) in top_pairs]
yoy_list = []
geom_mean_list = []
for r in top_results:
    pair_name = r["pair"]
    pnl = r.get("pnl_series")
    if pnl is None or pnl.empty:
        continue
    pnl = pnl.copy()
    if not hasattr(pnl.index, "year"):
        pnl.index = pd.to_datetime(pnl.index)
    by_year = pnl.groupby(pnl.index.year).sum()
    yearly_pnl = by_year.iloc[:, 0] if by_year.ndim > 1 else by_year
    yearly_ret_pct = (yearly_pnl / CAPITAL * 100).round(2)
    yoy_list.append(pd.DataFrame({pair_name: yearly_ret_pct}))
    r_frac = yearly_pnl / CAPITAL
    g = (np.prod(1 + r_frac) ** (1 / len(r_frac)) - 1) * 100 if len(r_frac) > 0 else np.nan
    geom_mean_list.append({"pair": pair_name, "geom_mean_ret_pct": round(g, 2)})
yoy_table = pd.concat(yoy_list, axis=1) if yoy_list else pd.DataFrame()
yoy_table.index.name = "year"
print("Year-over-year return (% of CAPITAL per year):")
display(yoy_table)
geom_mean_df = pd.DataFrame(geom_mean_list)
print("Geometric mean of yearly returns (%):")
display(geom_mean_df)

Year-over-year return (% of CAPITAL per year):

/var/folders/xz/2ks9m60d53gg2lrfyqwfk7kr0000gn/T/ipykernel_14648/2240866599.py:19: RuntimeWarning: invalid value encountered in scalar power
  g = (np.prod(1 + r_frac) ** (1 / len(r_frac)) - 1) * 100 if len(r_frac) > 0 else np.nan
/var/folders/xz/2ks9m60d53gg2lrfyqwfk7kr0000gn/T/ipykernel_14648/2240866599.py:19: RuntimeWarning: invalid value encountered in scalar power
  g = (np.prod(1 + r_frac) ** (1 / len(r_frac)) - 1) * 100 if len(r_frac) > 0 else np.nan

,NCLH/VXF,CCL/EBAY,CURB/TAN,CURB/SOXX,NCLH/TIP,OXY/YOU,DXC/VSTS,NCLH/WAFD,NCLH/RJF,EMBC/IRDM,...,HWM/NRG,EWZ/JNJ,SPY/VTIP,DXC/PZZA,COP/WAY,NBHC/WAFD,D/GEV,INN/PLD,NABL/SRPT,EMBC/KTB
year,,,,,,,,,,,,,,,,,,,,,
2020,189.21,392.97,NaN,NaN,786.57,NaN,NaN,29.02,202.66,NaN,...,38.10,274.15,91.67,190.90,NaN,77.88,NaN,361.52,NaN,NaN
2021,280.86,248.17,NaN,NaN,174.73,NaN,NaN,554.90,560.27,NaN,...,107.77,134.73,59.39,298.11,NaN,109.83,NaN,59.63,53.96,NaN
2022,158.77,101.00,NaN,NaN,-0.69,99.12,NaN,231.28,280.80,299.05,...,72.72,288.61,-22.81,243.95,NaN,362.12,NaN,114.34,126.76,261.10
2023,255.85,158.12,NaN,NaN,-60.38,17.96,16.02,49.74,171.25,302.05,...,-0.46,287.95,167.54,40.89,NaN,213.04,NaN,151.41,75.33,149.12
2024,130.26,45.39,7.41,8.32,191.32,50.92,162.67,411.91,209.93,132.43,...,500.35,82.38,145.18,59.43,55.66,335.90,49.51,-24.97,125.41,126.77
2025,0.00,68.20,23.64,27.68,0.00,-3.23,24.78,0.00,29.30,0.00,...,66.60,-4.39,129.13,3.60,0.00,0.00,8.20,41.33,36.08,247.85

Geometric mean of yearly returns (%):

         pair  geom_mean_ret_pct
0    NCLH/VXF             148.16
1    CCL/EBAY             145.28
2    CURB/TAN              15.24
3   CURB/SOXX              17.60
4    NCLH/TIP              74.18
5     OXY/YOU              36.09
6    DXC/VSTS              56.09
7   NCLH/WAFD             144.68
8    NCLH/RJF             206.39
9   EMBC/IRDM             147.12
10  APLS/SOLV              68.05
11    NCLH/SM              78.50
12   BDX/TTWO              48.55
13   SNCY/VIS             164.84
14    AXL/UPS                NaN
15     EG/MBC              43.52
16    EG/SOLV              16.86
17  AHCO/SOLV              43.91
18   CCL/SNEX             130.09
19   BNO/EMBC              35.07
20   GPN/VSTS              38.25
21    EMBC/KR             -18.53
22   REYN/VFH              68.32
23  APLE/VSTS              21.12
24    GPI/SYK             132.22
25  EMBC/WINA                NaN
26    EMBC/GO              80.21
27  CURB/INSP               4.65
28  HAFC/SOLV              67.16
29  CURB/IRDM              18.83
30   EMBC/SXI             143.18
31   PMT/SOLV              30.13
32   CURB/DOW               4.92
33  PFBC/SOLV              74.31
34    IQV/OXY              73.84
35  GDEN/VSTS              29.88
36   CERT/TIP              60.92
37   REYN/VAW              41.88
38    DGX/WMT              46.16
39   CURB/TFX               7.56
40    HWM/NRG              91.52
41    EWZ/JNJ             147.69
42   SPY/VTIP              81.24
43   DXC/PZZA             112.73
44    COP/WAY              24.76
45  NBHC/WAFD             148.48
46      D/GEV              27.19
47    INN/PLD              86.52
48  NABL/SRPT              79.77
49   EMBC/KTB             190.24

In [20]:
import numpy as np

# Full result dicts for top N (with pnl_series)
top_pairs = set(zip(top["ticker_a"], top["ticker_b"]))
top_results = [r for r in results if (r["ticker_a"], r["ticker_b"]) in top_pairs]

yoy_list = []
geom_mean_list = []
for r in top_results:
    pair_name = r["pair"]
    pnl = r.get("pnl_series")
    if pnl is None or pnl.empty:
        continue
    pnl = pnl.copy()
    if not hasattr(pnl.index, "year"):
        pnl.index = pd.to_datetime(pnl.index)
    by_year = pnl.groupby(pnl.index.year).sum()
    yearly_pnl = by_year.iloc[:, 0] if by_year.ndim > 1 else by_year
    yearly_ret_pct = (yearly_pnl / CAPITAL * 100).round(2)
    yoy_list.append(pd.DataFrame({pair_name: yearly_ret_pct}))
    r_frac = yearly_pnl / CAPITAL
    g = (np.prod(1 + r_frac) ** (1 / len(r_frac)) - 1) * 100 if len(r_frac) > 0 else np.nan
    geom_mean_list.append({"pair": pair_name, "geom_mean_ret_pct": round(g, 2)})

yoy_table = pd.concat(yoy_list, axis=1) if yoy_list else pd.DataFrame()
yoy_table.index.name = "year"
print("Year-over-year return (% of CAPITAL per year):")
display(yoy_table)

geom_mean_df = pd.DataFrame(geom_mean_list)
print("Geometric mean of yearly returns (%):")
display(geom_mean_df)

Year-over-year return (% of CAPITAL per year):

/var/folders/xz/2ks9m60d53gg2lrfyqwfk7kr0000gn/T/ipykernel_14648/3237960600.py:22: RuntimeWarning: invalid value encountered in scalar power
  g = (np.prod(1 + r_frac) ** (1 / len(r_frac)) - 1) * 100 if len(r_frac) > 0 else np.nan
/var/folders/xz/2ks9m60d53gg2lrfyqwfk7kr0000gn/T/ipykernel_14648/3237960600.py:22: RuntimeWarning: invalid value encountered in scalar power
  g = (np.prod(1 + r_frac) ** (1 / len(r_frac)) - 1) * 100 if len(r_frac) > 0 else np.nan

,NCLH/VXF,CCL/EBAY,CURB/TAN,CURB/SOXX,NCLH/TIP,OXY/YOU,DXC/VSTS,NCLH/WAFD,NCLH/RJF,EMBC/IRDM,...,HWM/NRG,EWZ/JNJ,SPY/VTIP,DXC/PZZA,COP/WAY,NBHC/WAFD,D/GEV,INN/PLD,NABL/SRPT,EMBC/KTB
year,,,,,,,,,,,,,,,,,,,,,
2020,189.21,392.97,NaN,NaN,786.57,NaN,NaN,29.02,202.66,NaN,...,38.10,274.15,91.67,190.90,NaN,77.88,NaN,361.52,NaN,NaN
2021,280.86,248.17,NaN,NaN,174.73,NaN,NaN,554.90,560.27,NaN,...,107.77,134.73,59.39,298.11,NaN,109.83,NaN,59.63,53.96,NaN
2022,158.77,101.00,NaN,NaN,-0.69,99.12,NaN,231.28,280.80,299.05,...,72.72,288.61,-22.81,243.95,NaN,362.12,NaN,114.34,126.76,261.10
2023,255.85,158.12,NaN,NaN,-60.38,17.96,16.02,49.74,171.25,302.05,...,-0.46,287.95,167.54,40.89,NaN,213.04,NaN,151.41,75.33,149.12
2024,130.26,45.39,7.41,8.32,191.32,50.92,162.67,411.91,209.93,132.43,...,500.35,82.38,145.18,59.43,55.66,335.90,49.51,-24.97,125.41,126.77
2025,0.00,68.20,23.64,27.68,0.00,-3.23,24.78,0.00,29.30,0.00,...,66.60,-4.39,129.13,3.60,0.00,0.00,8.20,41.33,36.08,247.85

Geometric mean of yearly returns (%):

         pair  geom_mean_ret_pct
0    NCLH/VXF             148.16
1    CCL/EBAY             145.28
2    CURB/TAN              15.24
3   CURB/SOXX              17.60
4    NCLH/TIP              74.18
5     OXY/YOU              36.09
6    DXC/VSTS              56.09
7   NCLH/WAFD             144.68
8    NCLH/RJF             206.39
9   EMBC/IRDM             147.12
10  APLS/SOLV              68.05
11    NCLH/SM              78.50
12   BDX/TTWO              48.55
13   SNCY/VIS             164.84
14    AXL/UPS                NaN
15     EG/MBC              43.52
16    EG/SOLV              16.86
17  AHCO/SOLV              43.91
18   CCL/SNEX             130.09
19   BNO/EMBC              35.07
20   GPN/VSTS              38.25
21    EMBC/KR             -18.53
22   REYN/VFH              68.32
23  APLE/VSTS              21.12
24    GPI/SYK             132.22
25  EMBC/WINA                NaN
26    EMBC/GO              80.21
27  CURB/INSP               4.65
28  HAFC/SOLV              67.16
29  CURB/IRDM              18.83
30   EMBC/SXI             143.18
31   PMT/SOLV              30.13
32   CURB/DOW               4.92
33  PFBC/SOLV              74.31
34    IQV/OXY              73.84
35  GDEN/VSTS              29.88
36   CERT/TIP              60.92
37   REYN/VAW              41.88
38    DGX/WMT              46.16
39   CURB/TFX               7.56
40    HWM/NRG              91.52
41    EWZ/JNJ             147.69
42   SPY/VTIP              81.24
43   DXC/PZZA             112.73
44    COP/WAY              24.76
45  NBHC/WAFD             148.48
46      D/GEV              27.19
47    INN/PLD              86.52
48  NABL/SRPT              79.77
49   EMBC/KTB             190.24